export const errorHandler = (err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({ error: 'Si Ã¨ verificato un errore interno del server.' });
  };